server:
  port: 8762

eureka:
  instance:
    hostname: 192.168.2.103
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  config: classpath:logback-spring.xml